
#define SQLITE_ENABLE_LOAD_EXTENSION
#define SQLITE_ENABLE_COLUMN_METADATA

#define SQLITE_ALLOW_URI_AUTHORITY
#define SQLITE_ENABLE_ATOMIC_WRITE
#define SQLITE_ENABLE_BATCH_ATOMIC_WRITE

#define SQLITE_ENABLE_BYTECODE_VTAB
#define SQLITE_ENABLE_COLUMN_METADATA

#define SQLITE_ENABLE_BYTECODE_VTAB
#define SQLITE_ENABLE_COLUMN_METADATA

#define SQLITE_ENABLE_FTS4
#define SQLITE_ENABLE_FTS5
#define SQLITE_ENABLE_GEOPOLY

#define SQLITE_ENABLE_MATH_FUNCTIONS
#define SQLITE_ENABLE_JSON1
#define SQLITE_ENABLE_MEMORY_MANAGEMENT

#define SQLITE_ENABLE_OFFSET_SQL_FUNC
#define SQLITE_ENABLE_PREUPDATE_HOOK

#define SQLITE_ENABLE_RBU
#define SQLITE_ENABLE_RTREE
#define SQLITE_ENABLE_SORTER_REFERENCES

#define SQLITE_ENABLE_SESSION
#define SQLITE_ENABLE_PREUPDATE_HOOK

#define SQLITE_ENABLE_UPDATE_DELETE_LIMIT

#define SQLITE_SOUNDEX

